[phases.setup]
nixPkgs = ["php", "php.packages.composer", "nodejs", "mariadb"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cp .env.example .env",
  "php artisan key:generate",
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan session:table && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
